services:
  - type: web
    name: recipe-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: recipe_manager
    healthCheckPath: /
    autoDeploy: true 